### ISSUE TITLE
Arm64 Support

### ISSUE THREAD

**Issue by giovannicandido** [paketo-buildpacks/new-relic#136]
## Describe the Enhancement

It would be awesome if this pack supports ARM64 builds. I know there is a ongoing discussion from the buildpack community around this topic, and currently we don't have a general solution, but I did have success in build for ARM64 a spring boot application using the following builder:

```
tasks.bootBuildImage {
    builder.set("dashaun/builder:tiny")
    buildpacks.set(listOf( "urn:cnb:builder:paketo-buildpacks/java"))
}
```

But if a set the newrelic pack, I get this error: `fork/exec /cnb/buildpacks/paketo-buildpacks_new-relic/7.6.1/bin/detect: exec format error`
Which means this pack is not compiled with a ARM64 architecture. This is the config used:

```
tasks.bootBuildImage {
    builder.set("dashaun/builder:tiny")
    buildpacks.set(listOf( "urn:cnb:builder:paketo-buildpacks/java", "docker.io/paketobuildpacks/new-relic"))
    bindings.set(listOf(project.rootDir.absolutePath + "/buildpack/bindings/new-relic:/platform/bindings/new-relic"))
}
```

Check https://github.com/dashaun/paketo-arm64 for this work around.

Steps to reproduce: Create a project in https://start.spring.io/ just with spring web dependency for test. 
Add the configuration above in build.gradle
Run the command:

```
./gradlew bootBuildImage
```

This will generate a optimized container using the the spring boot buildings, verified its working on Oracle Cloud ARM64 Machine!

## Possible Solution

I'm not sure about the specifics, but maybe just release a image builded in arm64 emulator or native machine and it can work. Please check `docker buildx` for cross compilation in docker.

## Motivation

ARM64 are cheaper and available in many mainstrain cloud providers. Developer machines on apple silicon will also apreciate.
I have moved all my kubernetes cluster to ARM64 and I'm experimenting with buildpacks to build a more optimized image, but lack of oficial support for ARM64 is a blocker. I'm considering not using new relic, or setup in a different workaround (maybe editing the final image?) or maybe do not use buildpacks for the moment, but It is close to work for my specific case!

**Comment by dmikusa** [comment]
We are not providing ARM64 builds right now. It is on the roadmap and we working towards it as quickly as possible. Because this is a larger workstream for us, I'm going to close out this issue. You can follow the Paketo blog, we'll absolutely be posting more as we make progress with ARM64 support.

In the meantime, you can build and package your own buildpacks as ARM64 buildpacks using the instructions in this repo: https://github.com/dmikusa/paketo-arm64#package-your-buildpacks. It's the find general steps at the top, you can also see the scripts for the commands being run (although the script is not meant to build individual buildpacks). That is roughly the same process that @dashaun follows with his builder, he just doesn't package up this particular buildpack.

The other option would be to manually install/include the New Relic agent for the time being. I don't know exactly what that process would look like though. If you can get Maven/Gradle to bundle in the required JAR files with your executable JAR, you might be able to pass through the additional arguments in the `JAVA_TOOL_OPTIONS` env variable at runtime to enable the agent.
